---
abstract: 'Google API Discovery and SDK'
author:
  - 'Peter Scott <localshop@cpan.org>'
build_requires:
  Cwd: '0'
  Data::Dumper: '0'
  Email::Simple: '0'
  FindBin: '0'
  JSON: '0'
  MIME::Base64: '0'
  Sub::Override: '0'
  Test::More: '0'
  Test::Needs: '0'
  strict: '0'
  warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.012, CPAN::Meta::Converter version 2.150010'
license: apache
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-GoogleAPI-Client
requires:
  CHI: '0'
  Carp: '0'
  Config::JSON: '0'
  Crypt::JWT: '0'
  Data::Dump: '0'
  Hash::Slice: '0'
  List::Util: '1.45'
  Mojo::Base: '0'
  Mojo::UserAgent: '0'
  Mojolicious: '7.12'
  Mojolicious::Lite: '0'
  Mojolicious::Plugin::OAuth2: '1.5'
  Moo: '0'
  MooX::Singleton: '0'
  Net::EmptyPort: '0'
  Path::Class: '0'
  Tie::File: '0'
  feature: '0'
  perl: v5.14.4
  strictures: '0'
resources:
  bugtracker: https://github.com/pscott-au/WebService-GoogleAPI-Client/issues
  homepage: https://pscott-au.github.io/WebService-GoogleAPI-Client/
  repository: git://github.com/pscott-au/WebService-GoogleAPI-Client.git
version: 0.20.1
x_generated_by_perl: v5.28.0
x_serialization_backend: 'YAML::Tiny version 1.73'
